base_features:
- open
- high
- low
- close
- adjust
- change
- percent_change
- matching_volume
- matching_value
- negotiate_volume
- negotiate_value
- number_of_buy_orders
- buy_volume
- average_volume_per_buy_order
- number_of_sell_orders
- sell_volume
- average_volume_per_sell_order
- net_volume
batch_size: 32
epochs: 10000
forecast_window_size: 1
learning_rate: 1.0e-05
loss_fn: MSE
max_lookback_window_size: 5
min_lookback_window_size: 5
model_architecture: CNN
model_params: {}
notebook_name: cnn_vn_index_6
optimizer: ADAM
patience: 100
random_seed: 18
scaler_type: MINMAX
stock_code: vn_index
test_end_date: '2026-02-26'
test_start_date: '2024-01-01'
train_end_date: '2021-12-31'
train_start_date: '2000-01-01'
validation_end_date: '2023-12-31'
validation_start_date: '2022-01-01'
