# LOGGER
LOGGER_LOG_DIR = "logs"
LOGGER_LOG_FILE_NAME = f"{LOGGER_LOG_DIR}/app"


# TABULAR DATABASE

# POSTGRESQL
POSTGRESQL_DEFAULT_HOST = "localhost"
POSTGRESQL_DEFAULT_USER = "postgres"
POSTGRESQL_DEFAULT_PASSWORD = "changeme"
POSTGRESQL_DEFAULT_PORT = 5432
POSTGRESQL_DEFAULT_DATABASE = "postgres"
POSTGRESQL_DEFAULT_SCHEMA = "public"


# WEB_SCRAPER
WEB_SCRAPER_MACROECONOMICS_FOLDER_NAME = "macroeconomics"
WEB_SCRAPER_STOCK_MARKET_FOLDER_NAME = "stock_market"
WEB_SCRAPER_ENTERPRISE_FOLDER_NAME = "enterprise"


# MACROECONOMICS
MACROECONOMICS_URL_GDP = "https://finance.vietstock.vn/du-lieu-vi-mo/43/thu-nhap.htm"
