# LOGGER
LOGGER_LOG_DIR = "logs"
LOGGER_LOG_FILE_NAME = f"{LOGGER_LOG_DIR}/app"


# TABULAR DATABASE

# POSTGRESQL
POSTGRESQL_DEFAULT_HOST = "localhost"
POSTGRESQL_DEFAULT_USER = "postgres"
POSTGRESQL_DEFAULT_PASSWORD = "changeme"
POSTGRESQL_DEFAULT_PORT = 5432
POSTGRESQL_DEFAULT_DATABASE = "postgres"
POSTGRESQL_DEFAULT_SCHEMA = "public"
